import { useState, useCallback, useRef } from 'react';
import { isSupabaseConfigured, getSupabaseClient } from '../services/supabase';
import { toast } from '../components/Toast';
import { stripPendingBlocks } from '../utils/editorUtils';

const LOCAL_PROJECTS_KEY = 'ai_book_writer_projects';

// A very large note (long batch-generated document, or one with several
// pasted/generated images inlined as base64) can exceed Supabase's request
// body size limit. That failure used to be swallowed into the `error` state
// only — which nothing ever rendered — so a save could silently fail on a
// big note and the student would only discover it much later with no clue
// why. Surface it immediately and explain the likely cause when the note is
// large enough for that to be it.
function describeSaveFailure(err: any, content: string): string {
  const sizeMB = new Blob([content]).size / (1024 * 1024);
  const base = err?.message || 'Unknown error';
  if (sizeMB > 3) {
    return `Could not save — this note is ~${sizeMB.toFixed(1)}MB, likely too large to sync. Copy/export it now (PDF or Word) before doing anything else. (${base})`;
  }
  return `Could not save your note: ${base}`;
}

interface LocalProject {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
  content: string | null;
  tags: string[];
  entry_date: string | null;
}

// Tag applied to every note generated by the Daily Current Affairs pipeline —
// filtered on in ProjectsPanel and used to scope the date-range combined read.
export const CURRENT_AFFAIRS_TAG = 'current-affairs';

export interface ProjectCreateMeta {
  tags?: string[];
  entryDate?: string | null; // 'YYYY-MM-DD'
}

// The `tags`/`entry_date` columns ship via a migration (see
// supabase/migrations/*_current_affairs_tags.sql) that has to be applied by
// hand against each deployment's own Supabase project — this app has no way
// to run it itself. Until that's done, any query touching those columns
// fails outright (Postgres "column does not exist" / PostgREST's stale
// schema-cache equivalent). Detected here so project save/list/load degrade
// to the pre-migration shape instead of breaking every save in the app.
function isMissingColumnError(err: any): boolean {
  const code = err?.code;
  const msg = String(err?.message || '').toLowerCase();
  return code === '42703' || code === 'PGRST204' || (msg.includes('column') && msg.includes('does not exist'));
}

function getLocalProjects(): LocalProject[] {
  try {
    return JSON.parse(localStorage.getItem(LOCAL_PROJECTS_KEY) || '[]');
  } catch {
    return [];
  }
}

function saveLocalProjects(projects: LocalProject[]) {
  localStorage.setItem(LOCAL_PROJECTS_KEY, JSON.stringify(projects));
}

export type ProjectMeta = {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
  tags: string[];
  entry_date: string | null;
};

function localToMeta(p: LocalProject): ProjectMeta {
  return {
    id: p.id,
    name: p.name,
    created_at: p.created_at,
    updated_at: p.updated_at,
    tags: p.tags ?? [],
    entry_date: p.entry_date ?? null,
  };
}

// Pre-load local projects synchronously so the panel is instant
function loadInitialProjects(): ProjectMeta[] {
  if (isSupabaseConfigured) return [];
  return getLocalProjects()
    .map(localToMeta)
    .sort((a, b) => b.updated_at.localeCompare(a.updated_at));
}

export function useProjects() {
  const [projects, setProjects] = useState<ProjectMeta[]>(loadInitialProjects);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeProjectId, setActiveProjectId] = useState<string | null>(null);

  // Guard: prevent concurrent fetches
  const fetchingRef = useRef(false);
  // Track if we've ever fetched from Supabase
  const hasFetchedRef = useRef(!isSupabaseConfigured);
  // Throttles repeated save-failure toasts — a persistent problem (offline,
  // a note stuck over the size limit) fires on every 3s autosave tick, and
  // without this a few minutes of typing while offline stacks up a wall of
  // near-identical "Could not save…" toasts.
  const lastSaveToastRef = useRef<{ message: string; at: number } | null>(null);
  const SAVE_TOAST_COOLDOWN_MS = 8000;
  const toastSaveFailure = useCallback((err: any, content: string) => {
    const message = describeSaveFailure(err, content);
    const now = Date.now();
    const last = lastSaveToastRef.current;
    if (last && last.message === message && now - last.at < SAVE_TOAST_COOLDOWN_MS) return;
    lastSaveToastRef.current = { message, at: now };
    toast.error(message);
  }, []);

  const fetchProjects = useCallback(async (force = false) => {
    // For local storage — always instant, no loading needed
    if (!isSupabaseConfigured) {
      const local = getLocalProjects()
        .map(localToMeta)
        .sort((a, b) => b.updated_at.localeCompare(a.updated_at));
      setProjects(local);
      return;
    }

    // For Supabase — skip if already loading or already fetched (unless forced)
    if (fetchingRef.current) return;
    if (hasFetchedRef.current && !force) return;

    fetchingRef.current = true;
    setLoading(true);
    setError(null);
    try {
      const sb = getSupabaseClient();
      let { data, error: sbErr }: { data: any[] | null; error: any } = await sb
        .from('projects')
        .select('id, name, created_at, updated_at, tags, entry_date')
        .order('updated_at', { ascending: false });
      if (sbErr && isMissingColumnError(sbErr)) {
        // Pre-migration project: fall back to the plain shape so history
        // still loads (just without tags/dates) instead of erroring out.
        ({ data, error: sbErr } = await sb
          .from('projects')
          .select('id, name, created_at, updated_at')
          .order('updated_at', { ascending: false }));
      }
      if (sbErr) throw sbErr;
      setProjects(((data as ProjectMeta[]) || []).map(p => ({ ...p, tags: p.tags ?? [], entry_date: p.entry_date ?? null })));
      hasFetchedRef.current = true;
    } catch (e: any) {
      setError(e?.message || 'Failed to load projects');
    } finally {
      setLoading(false);
      fetchingRef.current = false;
    }
  }, []);

  // Which server revision each note's in-memory copy came from: the content
  // as it was read, and the `updated_at` stamped on it. saveProject writes
  // against that stamp, so a copy that has gone stale — a tab left open
  // while the background worker appended fifty answers — can no longer
  // overwrite the newer version. This is the whole defence against the
  // "notes came back with answers missing" failure: without it, the last
  // writer simply wins, and the last writer is usually the tab holding the
  // oldest copy.
  const baseRef = useRef<Map<string, { content: string; updatedAt: string }>>(new Map());

  // Called on first panel open — only fetches once unless forced
  const onPanelOpen = useCallback(() => {
    fetchProjects(false);
  }, [fetchProjects]);

  // Called on manual sync button — always re-fetches
  const syncProjects = useCallback(() => {
    fetchProjects(true);
  }, [fetchProjects]);

  // Intentionally does NOT swallow errors into a `null` return — a failed
  // fetch (network drop, RLS hiccup) and a project that's genuinely empty
  // both used to look identical to the caller, which meant opening a
  // project during a network blip silently did nothing AND still let the
  // caller mark that project "active", so the next auto-save would have
  // overwritten it with whatever unrelated document was already on screen.
  // Throwing here lets the caller tell the two cases apart and only flips
  // the active project on an actual successful load.
  const loadProjectContent = useCallback(async (id: string): Promise<string | null> => {
    if (isSupabaseConfigured) {
      const sb = getSupabaseClient();
      const { data, error: sbErr } = await sb
        .from('projects')
        .select('content, updated_at')
        .eq('id', id)
        .single();
      if (sbErr) throw sbErr;
      const row = data as { content: string | null; updated_at: string } | null;
      const content = row?.content ?? null;
      // Remember exactly which revision this copy came from — saveProject
      // refuses to overwrite anything newer than it.
      if (row) baseRef.current.set(id, { content: content ?? '', updatedAt: row.updated_at });
      return content;
    }
    const local = getLocalProjects();
    const p = local.find(lp => lp.id === id);
    return p?.content ?? null;
  }, []);

  const createProject = useCallback(async (name: string, rawContent: string, meta?: ProjectCreateMeta): Promise<ProjectMeta | null> => {
    // Same reason as saveProject: a live "writing…" placeholder is UI state,
    // not something a note should be created holding.
    const content = stripPendingBlocks(rawContent);
    const tags = meta?.tags ?? [];
    const entryDate = meta?.entryDate ?? null;
    try {
      if (isSupabaseConfigured) {
        const sb = getSupabaseClient();
        // RLS on `projects` requires auth.uid() = user_id. App.tsx
        // gates render on ensureSession(), so by the time createProject
        // is callable the cached session is always present — pull the
        // current user id from there.
        const { data: { user } } = await sb.auth.getUser();
        if (!user) throw new Error('Not signed in');
        let { data, error: sbErr } = await sb
          .from('projects')
          .insert({ name, content, user_id: user.id, tags, entry_date: entryDate })
          .select('id, name, created_at, updated_at, tags, entry_date')
          .single();
        if (sbErr && isMissingColumnError(sbErr)) {
          // Migration not applied yet on this deployment — save the project
          // without tags/date rather than failing the save entirely. The
          // Current Affairs tag is lost for this note until the migration
          // runs (see supabase/migrations/*_current_affairs_tags.sql).
          ({ data, error: sbErr } = await sb
            .from('projects')
            .insert({ name, content, user_id: user.id })
            .select('id, name, created_at, updated_at')
            .single());
        }
        if (sbErr) throw sbErr;
        const proj = { ...(data as ProjectMeta), tags: (data as any)?.tags ?? [], entry_date: (data as any)?.entry_date ?? null };
        // 200-cap is enforced server-side by a trigger that deletes the
        // oldest-by-updated_at rows when count > 200. Mirror that locally
        // so the sidebar list reflects the cap without a refetch round-trip.
        setProjects(prev => {
          const next = [proj, ...prev];
          return next.length > 200 ? next.slice(0, 200) : next;
        });
        return proj;
      } else {
        const now = new Date().toISOString();
        const newProject: LocalProject = {
          id: crypto.randomUUID(),
          name,
          content,
          created_at: now,
          updated_at: now,
          tags,
          entry_date: entryDate,
        };
        const local = getLocalProjects();
        local.unshift(newProject);
        // Mirror the server-side 200-cap: keep the most-recent 200 in
        // localStorage so the offline fallback can't unbounded-grow.
        const capped = local.length > 200
          ? local.sort((a, b) => b.updated_at.localeCompare(a.updated_at)).slice(0, 200)
          : local;
        saveLocalProjects(capped);
        const meta = localToMeta(newProject);
        setProjects(prev => {
          const next = [meta, ...prev];
          return next.length > 200 ? next.slice(0, 200) : next;
        });
        return meta;
      }
    } catch (e: any) {
      setError(e?.message || 'Failed to create project');
      toastSaveFailure(e, content);
      return null;
    }
  }, []);

  // Called when a save found the note already changed by someone else —
  // in practice the background worker, which appends answers while a tab
  // sits open holding an older copy.
  //
  // The rule is that no writer may delete another writer's work. Since
  // every writer here APPENDS, the two versions almost always share a
  // common prefix, and merging is exact rather than a guess: take the
  // server's version (it has their additions) and re-apply whatever this
  // copy added on top of the shared base.
  const reconcileConflict = useCallback(async (
    sb: ReturnType<typeof getSupabaseClient>,
    id: string,
    base: { content: string; updatedAt: string },
    ours: string,
  ): Promise<boolean> => {
    const { data, error } = await sb
      .from('projects')
      .select('content, updated_at')
      .eq('id', id)
      .single();
    if (error) throw error;
    const row = data as { content: string | null; updated_at: string };
    const theirs = row.content ?? '';

    // Nothing of ours to add — adopt theirs and move on quietly.
    if (theirs === ours) {
      baseRef.current.set(id, { content: theirs, updatedAt: row.updated_at });
      return true;
    }

    // Our copy is the base plus our own additions: replay those on top of
    // their newer version. This is the case that matters — it keeps BOTH
    // the worker's answers and whatever this tab added.
    if (ours.startsWith(base.content)) {
      const ourAdditions = ours.slice(base.content.length);
      const merged = ourAdditions ? theirs + ourAdditions : theirs;
      if (merged === theirs) {
        baseRef.current.set(id, { content: theirs, updatedAt: row.updated_at });
        return true;
      }
      const stamp = new Date().toISOString();
      const { data: w, error: wErr } = await sb
        .from('projects')
        .update({ content: merged, updated_at: stamp })
        .eq('id', id)
        .eq('updated_at', row.updated_at)
        .select('id');
      if (wErr) throw wErr;
      if (w && w.length > 0) {
        baseRef.current.set(id, { content: merged, updatedAt: stamp });
        return true;
      }
      // Changed again mid-merge. Leave it; the next autosave tick retries
      // from the newer revision rather than racing this one.
      return false;
    }

    // Our copy diverged from the base (an edit or deletion in the middle of
    // the document), so the additions can't be isolated. Refuse to write:
    // discarding a save is recoverable, overwriting someone else's answers
    // is not. Adopt their revision as the new base so the canvas sync pulls
    // it in and the next save starts from something current.
    baseRef.current.set(id, { content: theirs, updatedAt: row.updated_at });
    toast.warning('This note was updated in the background while it was open — reloading it so nothing is lost. Re-apply your last edit if it is missing.');
    return false;
  }, []);

  const saveProject = useCallback(async (id: string, rawContent: string): Promise<boolean> => {
    // A "✍️ writing the answer…" placeholder is live UI state, never note
    // content. The 3s autosave fires while one is on the canvas, so without
    // this a tab closed (or a note switched away from) mid-generation
    // persists that block into the note permanently — it reopens showing an
    // answer that is forever about to be written.
    const content = stripPendingBlocks(rawContent);
    try {
      const now = new Date().toISOString();
      if (isSupabaseConfigured) {
        const sb = getSupabaseClient();
        const base = baseRef.current.get(id);

        // Write ONLY against the revision this copy was read from. If the
        // note has moved on since — the background worker appended answers
        // while this tab sat in the background, where its refresh timer is
        // throttled or suspended outright — zero rows match and nothing is
        // overwritten. Previously this was a bare update by id: last writer
        // wins, and the last writer is routinely the tab holding the oldest
        // copy. That is how a note comes back with dozens of answers gone.
        let query = sb.from('projects').update({ content, updated_at: now }).eq('id', id);
        if (base) query = query.eq('updated_at', base.updatedAt);
        const { data: written, error: sbErr } = await query.select('id');
        if (sbErr) throw sbErr;

        if (base && (!written || written.length === 0)) {
          const reconciled = await reconcileConflict(sb, id, base, content);
          if (!reconciled) return false;
        } else {
          baseRef.current.set(id, { content, updatedAt: now });
        }
      } else {
        const local = getLocalProjects();
        const idx = local.findIndex(p => p.id === id);
        if (idx !== -1) {
          local[idx].content = content;
          local[idx].updated_at = now;
          saveLocalProjects(local);
        }
      }
      // Optimistic update — no refetch needed
      setProjects(prev =>
        [...prev.map(p => p.id === id ? { ...p, updated_at: now } : p)]
          .sort((a, b) => b.updated_at.localeCompare(a.updated_at))
      );
      return true;
    } catch (e: any) {
      setError(e?.message || 'Failed to save project');
      toastSaveFailure(e, content);
      return false;
    }
  }, [reconcileConflict]);

  const renameProject = useCallback(async (id: string, name: string): Promise<boolean> => {
    try {
      const now = new Date().toISOString();
      if (isSupabaseConfigured) {
        const sb = getSupabaseClient();
        const { error: sbErr } = await sb
          .from('projects')
          .update({ name, updated_at: now })
          .eq('id', id);
        if (sbErr) throw sbErr;
      } else {
        const local = getLocalProjects();
        const idx = local.findIndex(p => p.id === id);
        if (idx !== -1) { local[idx].name = name; local[idx].updated_at = now; saveLocalProjects(local); }
      }
      // Optimistic update
      setProjects(prev => prev.map(p => p.id === id ? { ...p, name, updated_at: now } : p));
      return true;
    } catch {
      return false;
    }
  }, []);

  const deleteProject = useCallback(async (id: string): Promise<boolean> => {
    try {
      if (isSupabaseConfigured) {
        const sb = getSupabaseClient();
        const { error: sbErr } = await sb.from('projects').delete().eq('id', id);
        if (sbErr) throw sbErr;
      } else {
        const local = getLocalProjects().filter(p => p.id !== id);
        saveLocalProjects(local);
      }
      // Optimistic update
      setProjects(prev => prev.filter(p => p.id !== id));
      setActiveProjectId(prev => (prev === id ? null : prev));
      return true;
    } catch {
      return false;
    }
  }, []);

  // Combined "read by date range" — pulls every project carrying `tag` whose
  // entry_date falls within [start, end] (inclusive, 'YYYY-MM-DD'), content
  // included, oldest first. Used to build the merged multi-day reading view;
  // does not touch `projects` state, so it can't disturb the sidebar list.
  const fetchProjectsByDateRange = useCallback(async (
    tag: string,
    start: string,
    end: string,
  ): Promise<{ id: string; name: string; content: string; entry_date: string | null }[]> => {
    if (isSupabaseConfigured) {
      const sb = getSupabaseClient();
      const { data, error: sbErr } = await sb
        .from('projects')
        .select('id, name, content, entry_date')
        .contains('tags', [tag])
        .gte('entry_date', start)
        .lte('entry_date', end)
        .order('entry_date', { ascending: true });
      if (sbErr) {
        if (isMissingColumnError(sbErr)) {
          throw new Error('The Current Affairs date-range migration hasn\'t been applied to this database yet — see supabase/migrations/.');
        }
        throw sbErr;
      }
      return ((data as any[]) || []).map(p => ({
        id: p.id, name: p.name, content: p.content || '', entry_date: p.entry_date ?? null,
      }));
    }
    const local = getLocalProjects()
      .filter(p => (p.tags ?? []).includes(tag) && p.entry_date && p.entry_date >= start && p.entry_date <= end)
      .sort((a, b) => (a.entry_date || '').localeCompare(b.entry_date || ''));
    return local.map(p => ({ id: p.id, name: p.name, content: p.content || '', entry_date: p.entry_date }));
  }, []);

  return {
    projects,
    loading,
    error,
    activeProjectId,
    setActiveProjectId,
    fetchProjects: onPanelOpen,
    fetchProjectsByDateRange,
    syncProjects,
    loadProjectContent,
    createProject,
    saveProject,
    renameProject,
    deleteProject,
    isSupabaseConfigured,
  };
}
