export enum GenerationStatus {
  IDLE = 'IDLE',
  GENERATING_CHAPTER = 'GENERATING_CHAPTER',
  GENERATING_TABLE = 'GENERATING_TABLE',
  GENERATING_IMAGE = 'GENERATING_IMAGE',
}

// Live "mind map" shown while a multi-step notes pipeline runs (Topic, Text,
// File or Transcript input, at Medium/Detailed/Deep level). Each section of
// the planned outline is a node whose status animates as it is generated.
// Nodes that were produced together by one API call (e.g. all the headings
// found inside one transcript/text chunk) share a `groupId` — clicking any of
// them re-runs the SAME regenerate call and replaces all of their content
// together, since that's the actual unit of generation.
export type MindmapNodeStatus = 'pending' | 'active' | 'done' | 'error' | 'skipped';

export interface MindmapLeaf {
  id: string;
  label: string;
}

export interface MindmapNode {
  id: string;
  label: string;
  status: MindmapNodeStatus;
  children: MindmapLeaf[];
  // Nodes sharing a groupId were generated by (and are regenerated by) the
  // same call; clicking a 'done' node re-runs its group at higher depth,
  // clicking an 'error' node retries it.
  groupId: string;
}

export interface MindmapState {
  title: string;
  subtitle: string;
  nodes: MindmapNode[];
  // When set, the pipeline is paused on this node waiting for Retry/Skip/Finish.
  errorNodeId: string | null;
  // True once the main generation pass has finished (whether or not some
  // sections were skipped) — the overlay shows a "Done" button instead of
  // auto-closing, and the "add a point" field stays usable either way.
  complete: boolean;
  // True while an "add a point" request is in flight.
  addBusy: boolean;
}
