export enum GenerationStatus {
  IDLE = 'IDLE',
  GENERATING_CHAPTER = 'GENERATING_CHAPTER',
  GENERATING_TABLE = 'GENERATING_TABLE',
  GENERATING_IMAGE = 'GENERATING_IMAGE',
}

// Live "mind map" shown while a multi-step notes pipeline runs (Topic, Text,
// File or Transcript input, at Medium/Detailed/Deep level). Each section of
// the planned outline is a node whose status animates as it is generated.
// Nodes that were produced together by one API call (e.g. all the headings
// found inside one transcript/text chunk) share a `groupId` — clicking any of
// them re-runs the SAME regenerate call and replaces all of their content
// together, since that's the actual unit of generation.
export type MindmapNodeStatus = 'pending' | 'active' | 'done' | 'error' | 'skipped';

export interface MindmapLeaf {
  id: string;
  label: string;
}

export interface MindmapNode {
  id: string;
  label: string;
  status: MindmapNodeStatus;
  children: MindmapLeaf[];
  // Nodes sharing a groupId were generated by (and are regenerated by) the
  // same call; clicking a 'done' node re-runs its group at higher depth,
  // clicking an 'error' node retries it.
  groupId: string;
  // Optional per-section instruction the user attaches during the review
  // (approval) step, before generation starts — it's fed into this section's
  // first expansion so the initial draft already follows the guidance.
  instruction?: string;
}

export interface MindmapState {
  title: string;
  subtitle: string;
  nodes: MindmapNode[];
  // When set, the pipeline is paused on this node waiting for Retry/Skip/Finish.
  errorNodeId: string | null;
  // True while the pipeline is paused after building the outline, waiting for
  // the user to review/instruct and press "Approve & Generate". No expensive
  // expansion has run yet at this point.
  awaitingApproval: boolean;
  // True when this pipeline offers the "Restructure" action at the review
  // step. Source-grounded pipelines (transcript, text, files) do — their
  // outline is extracted mechanically and benefits from a cleanup pass. The
  // topic pipeline doesn't: its outline is already designed by the AI from
  // scratch, so there's nothing to restructure.
  canRestructure?: boolean;
  // True while the optional "Restructure" pass (offered during the review
  // step) is rewriting the outline — both review buttons are disabled until
  // it lands and the nodes are rebuilt.
  restructuring?: boolean;
  // True once the main generation pass has finished (whether or not some
  // sections were skipped) — the overlay shows a "Done" button instead of
  // auto-closing, and the "add a point" field stays usable either way.
  complete: boolean;
  // True while an "add a point" request is in flight.
  addBusy: boolean;
  // Set once a "Restructure" pass comes back, before it's applied — holds
  // both the original and the candidate outline so the review step can show
  // a before/after comparison and let the user pick one, instead of the
  // restructure silently overwriting the original outline.
  compareOutline?: {
    before: { heading: string; subheadings: string[] }[];
    after: { heading: string; subheadings: string[] }[];
  } | null;
}
